#!/usr/bin/env python3

from aoc2021 import run, run_day, run_all
import argparse
from os import path


def _file_type(file):
    if path.exists(file):
        return file
    else:
        raise argparse.ArgumentTypeError()


parser = argparse.ArgumentParser(formatter_class=lambda prog: argparse.HelpFormatter(
    prog, max_help_position=25, width=120))
parser.add_argument('-d', '--day', type=int)
parser.add_argument('-p', '--part', type=int)
parser.add_argument('-i', '--input', type=_file_type,
                    metavar='FILE', help='external input file')
parser.add_argument('-a', '--all', action='store_true', help='compute all')
args = parser.parse_args()

answers = []
if args.all:
    answers = run_all()
elif args.day:
    if args.part:
        answers.append(run(args.day, args.part, args.input))
    else:
        answers = run_day(args.day)
else:
    parser.print_help()
    exit(-1)

for answer in answers:
    print(f'{answer[0]} {answer[1]}')
    print(f'  answer  :\t {answer[2]}')
    print(f'  elapsed :\t {answer[3]}')
